# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: p1
#  vmImage: ubuntu-latest

#container: node:17-bullseye
#container: node:17-bullseye-slim
#container: node:17-alpine
#container: furiozoga/semantic-release:0.0.1
container: furiozoga/dotnetsdk:latest

steps:
<<<<<<< HEAD
- checkout: self
  clean: false
  persistCredentials: true

- script: echo Hello, world!
=======
- bash: echo Hello, world!
>>>>>>> 75f68fcdc26fbf07fdb16a5edd5e6d497f61ec0a
  displayName: 'Run a one-line script'

- bash: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #npm install
    uname -a
    echo $(System.AccessToken)
    git config -l
    cat /etc/issue
#    cat /proc/cpuinfo
    free
    node -v
    npm -v
    npx -v
    npx semantic-release -v
    npm ls -g
    npx semantic-release --no-ci
  displayName: 'Run a multi-line script'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world 2'
    failOnStderr: true